[versions]
#jvm
jvmTarget = "1.8"
#项目sdk版本配置
compileSdk = "34"
minSdk = "26"
targetSdk = "34"

#各模块打包版本配置
#app版本
appVersionCode = "1"
appVersionName = "1.0.0"
#log版本
versionCode-log = "1"
versionName-log = "1.0.0"

#插件版本
agp = "8.1.3"
org-jetbrains-kotlin-android = "1.9.0"


[plugins]
#application插件
application = { id = "com.android.application", version.ref = "agp" }
#kotlin插件
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
#android-lib插件
library = { id = "com.android.library", version.ref = "agp" }

